# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import requests
from PyQt5 import QtCore, QtGui, QtWidgets
import load




class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(465, 247)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gongsi = QtWidgets.QComboBox(self.centralwidget)
        self.gongsi.setGeometry(QtCore.QRect(121, 33, 211, 31))
        self.gongsi.setEditable(False)
        self.gongsi.setCurrentText("")
        self.gongsi.addItems(init_gongsi_combo())
        # 选中后执行get_com函数
        self.gongsi.currentTextChanged.connect(self.get_com)
        self.gongsi.setObjectName("gongsi")
        self.com = QtWidgets.QComboBox(self.centralwidget)
        self.com.setGeometry(QtCore.QRect(121, 73, 211, 31))
        self.com.setEditable(False)
        self.com.setCurrentText("")

        self.com.setObjectName("com")
        self.shouhou = QtWidgets.QComboBox(self.centralwidget)
        self.shouhou.setGeometry(QtCore.QRect(121, 110, 211, 31))
        self.shouhou.setCurrentText("")
        self.shouhou.setObjectName("shouhou")
        self.shouhou.addItems(init_shouhou_combo())
        self.login = QtWidgets.QPushButton(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(100, 170, 101, 41))
        self.login.setObjectName("login")
        self.close = QtWidgets.QPushButton(self.centralwidget)
        self.close.setGeometry(QtCore.QRect(260, 170, 101, 41))
        self.close.setObjectName("close")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.close.clicked.connect(MainWindow.close) # type: ignore
        self.login.clicked.connect(self.login_clicked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "售后登录"))
        self.login.setText(_translate("MainWindow", "远程"))
        self.close.setText(_translate("MainWindow", "关闭"))

    # 获取设备列表
    def get_com(self):
        self.com.clear()
        # 获取选中的文本
        gongsi = self.gongsi.currentText()
        url = "https://4bd6b408-e7ec-438f-83d2-8cba6cc6b874.bspapp.com/add/computerlist?name="+gongsi
        r = requests.get(url)
        global com
        com = r.json()["data"]
        # print(com)
        self.com.addItem('请选择')
        for i in com:
            self.com.addItem(i['computer_name'])
    def login_clicked(self):
        #   判断所有下拉框是否选中
        if self.gongsi.currentText() == '请选择':
            QtWidgets.QMessageBox.warning(self.centralwidget, "提示", "请选择公司")
            return
        if self.com.currentText() == '请选择':
            QtWidgets.QMessageBox.warning(self.centralwidget, "提示", "请选择设备")
            return
        if self.shouhou.currentText() == '请选择':
            QtWidgets.QMessageBox.warning(self.centralwidget, "提示", "请选择售后")
            return
        # 获取com选中的设备的账号密码
        text = self.com.currentText()
        for i in com:
            if i['computer_name'] == text:
                id = i['id']
                password = i['password']
                break
        print(id, password)
        # 初始化Remote
        Remote = load.Remote().input_account(id, password)


# 初始化请求获取商家信息
def init_gongsi():
    global info
    info = {}
    # 发送请求获取商家信息
    url = "https://4bd6b408-e7ec-438f-83d2-8cba6cc6b874.bspapp.com/add/clientlist"
    text = requests.get(url)
    # 解析商家信息
    info = text.json()["data"]

# 初始化公司下拉框数据
def init_gongsi_combo():
    combo = ['请选择']
    for i in info:
        combo.append(i["name"])
    return combo

# 初始化售后人员下拉框数据
def init_shouhou_combo():
    combo = ['请选择']
    # 发送请求
    url = "https://4bd6b408-e7ec-438f-83d2-8cba6cc6b874.bspapp.com/add/afterslist"
    text = requests.get(url)
    # 解析售后人员信息
    shouhou = text.json()["data"]
    for i in shouhou:
        combo.append(i["name"])
    return combo

if __name__ == "__main__":
    init_gongsi()

    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
